export const links = [
    [
        {
            title: 'Hepsiburada',
            links: [
                'Kullanıcı Bilgilerim',
                'İşlem Rehberi',
                'Hepsiburada.com Twitter Destek',
                'Mobil Uygulamalar',
                'Bilgi Toplumu Hizmetleri',
                'Güvenli Alışveriş Kılavuzu',
                'Kişisel Verilerin Korunması',
                'Bilgi Güvenliği Politikası',
                'İş Sağlığı ve Güvenliği Çevre Politikamız',
                'Hepsiburada ile E-ticaret Reklamcılığı',
                'Kurumsal Hediye Çeki',
            ],
        },
        {
            title: 'Kurumsal',
            links: [
                'Hakkımızda',
                'Vizyon & Misyon',
                'Kilometre Taşları',
                'Yönetim',
                'Kurumsal Sosyal Sorumluluk',
                'İş Ortaklarımız',
                'Tedarikçi Olmak İstiyorum',
                'Hepsipay İşyeri Olmak İstiyorum',
                'Tedarikçi Davranış Kuralları',
                'Girişimci Kadınlara Teknoloji Gücü',
                'Teslimat Noktası Olmak İstiyorum',
                "Hepsiburada'da Satıcı Ol",
                'Yatırımcı ilişkileri',
                'Çözüm merkezi',
                'Kariyer',
                'Basın Odası',
                'Bizden Haberler',
                'İletişim',
            ],
        },
    ],
    [
        {
            title: 'Kategoriler',
            links: [
                'Bilgisayar/Elektronik',
                'Telefon Fiyatları/Cep Telefonu',
                'Beyaz Eşya/Mutfak',
                'Foto/Kamera',
                'Spor/Outdoor',
                'Giyim/Ayakkabı',
                'Takı / Mücevher',
                'Saat / Gözlük / Aksesuar',
                'Kozmetik/Kişisel Bakım',
                'Anne & Bebek',
                'Oyuncak',
                'Kitap / Film / Müzik',
                'Hobi / Oyun Konsolu',
                'Kırtasiye / Ofis',
                'Oto Aksesuar / Yapı Market / Bahçe',
                'Kış Lastiği',
                'Ev Dekorasyonu/Mobilya',
                'Pet Shop/Süpermarket',
                'Duvar Kağıdı/Hesap Makinesi',
                'Led Tv/Parfüm',
                'Bebek Arabası/Bebek Bezi',
            ],
        },
        {
            title: 'Popüler Telefonlar',
            links: [
                'Android Telefonlar',
                'iPhone iOS Telefonlar',
                'Xiaomi Android Telefonlar',
                'Samsung Android Telefonlar',
            ],
        },
    ],
    [
        {
            title: 'Özel Sayfalar',
            links: [
                'Efsane Cuma',
                'Efsane Kasım',
                'Okul Alışverişi',
                'Sevgililer Günü',
                'Yılbaşı Hediyeleri',
                'Babalar Günü',
                'Black Friday',
                'Airpods',
                'Playstation 5',
                'Mi Band 6',
                'Evony Maske',
                'Bluetooth Kulaklık',
                'Maske',
                'Uçak Bileti',
                'Tüm Kategoriler',
                'Tüm Satıcılar',
                'Yazarlar',
            ],
        },
        {
            title: 'Popüler Markalar',
            links: [
                'Avon',
                'Samsung',
                'Adidas',
                'Nike',
                'Apple',
                'Vestel',
                'Bosch',
                'New Balance',
                'Defacto',
                'Lacoste',
                'Asus',
                'Lego',
                'Boyner',
                'Koton',
                'Fairy',
                'Mavi',
                'Under Armour',
                'Wasa',
                'Tüm Markalar',
            ],
        },
    ],
];

export const fashion = [
    'Etek/Elbise/Tunik/Trençkot',
    'Ayakkabı/Spor Ayakkabı',
    'Abiye Elbise/Çanta',
    'Nike Air Force/Nike Air Max',
];
